### ISSUE TITLE
local

### ISSUE THREAD

**Issue by ehartford** [basetenlabs/alpaca-7b-truss#2]
I see there's instructions to deploy on basetenlabs, but can I deploy it locally?

**Comment by kodxana** [comment]
That same question I would love to help adjust repo to support RunPod for example.

**Comment by amiruci** [comment]
Yes you can deploy it locally. This repo is a [Truss](https://truss.baseten.co/). You can Trusses [locally](https://truss.baseten.co/develop/localhost) and you can [deploy them](https://truss.baseten.co/#deploy-your-model) to different cloud services. 

@kodxana it won't be hard to add RunPod to [Truss](https://github.com/basetenlabs/truss). We're happy to review a PR and merge it.
